# This rule is not used by the project operator-demo itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the tenant.core.mellifluus.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: tenantenvironment-editor-role
rules:
- apiGroups:
  - tenant.core.mellifluus.io
  resources:
  - tenantenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenant.core.mellifluus.io
  resources:
  - tenantenvironments/status
  verbs:
  - get
