apiVersion: tenant.core.mellifluus.io/v1
kind: TenantEnvironment
metadata:
  labels:
    app.kubernetes.io/name: operator-demo
    app.kubernetes.io/managed-by: kustomize
  name: acme-corp
spec:
  displayName: "Acme Corporation"
  applicationImage: "nginx:1.25"
  applicationPort: 80
  replicas: 2
  resourceQuotas:
    cpuLimit: "2"
    memoryLimit: "4Gi"
    storageLimit: "10Gi"
    podLimit: 8
  database:
    # Uses shared PostgreSQL instance with separate database
    dedicatedInstance: false
